[package]
name = "drip-gui"
description = "Interactive node-graph frontend for Drip"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
cubecl = { version = "=0.11.0", default-features = false, features = ["std"] }
drip.workspace = true
drip-macros = { path = "../drip-macros" }
egui = "0.36"
egui-wgpu = "0.36"
egui-winit = "0.36"
env_logger = "0.11.11"
half = "2.7.1"
log = "0.4.34"
linkme = "0.3.37"
lcms2.workspace = true
rayon = "1.11"
pollster = "1.0.1"
rfd = "0.17.2"
serde = {version="1.0.229",features=["derive"]}
serde_json = "1.0.151"
tiff = { version = "0.11.3", default-features = false, features = ["deflate"] }
wgpu = "30"
winit = "0.30"

[target.'cfg(target_os = "linux")'.dependencies]
wayland-client = { version = "0.31", features = ["system"] }
wayland-protocols = { version = "0.32", features = ["client", "staging"] }

[lints]
workspace = true

[dev-dependencies]
egui_kittest = "0.36"
